# DEV Compose file.
# For a production file see: README.md

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  app:
    build: .
    env_file: .dev.env
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - 1234:8000
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://127.0.0.1:8000/cryptgeon/api/live/']
      interval: 1m
      timeout: 3s
      retries: 2
      start_period: 5s

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./examples/nginx/nginx-plain-prefix.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:1234
